### ISSUE TITLE
Client on  different router can not join the server

### ISSUE THREAD

**Issue by dushukai** [BoltEngine/Bolt-Tracker#133]
**Describe the bug**
If 2 players under different routers but under one same network. They cannot connect each other.

**To Reproduce**
1. First client connect to your home network and StartServer()
2. Set up another router at home but use the same WAN.
3. Second client StartClient() and connect to the session.
4. Client See error "OpJoinLobby is only allowed when connected to a Master Server. Current Server: GameServer, current State: Leaving"
5. Server See Error "[PUNCH FAILED] Local Player 1 with Remote Player 2"

**Expected behavior**
Expected No Error.

**Actual behavior**
Error shows and can not connect the the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/10824280/62259352-dfb94880-b3c2-11e9-9c1b-63647a02fcf4.png)
![image](https://user-images.githubusercontent.com/10824280/62259371-ee076480-b3c2-11e9-8767-a2949164c39f.png)

**Desktop (If applicable, please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
- Unity Version: 2018.3
- Bolt Version: 1.2.8
- Network Configuration: Photon Cloud

**Comment by herpdederp** [comment]
We've fixed the "OpJoin" issue and made other improvements to connecting in 1.2.9. Can you try with the latest Bolt version?

**Comment by dushukai** [comment]
I rollback to 1.2.9.
Now there's no error but there's the same warning text.
 "[PUNCH FAILED] Local Player 1 with Remote Player 2" on both client side and server side

And they are still not connected, everything just stuck, no more log.
![image](https://user-images.githubusercontent.com/10824280/62261191-50fbfa00-b3c9-11e9-8763-a82d4a40b34f.png)
![image](https://user-images.githubusercontent.com/10824280/62261207-5e18e900-b3c9-11e9-815b-c3bd4dc44c8d.png)

**Comment by ramonmelo** [comment]
@dushukai 
Can you run a test using an empty project with the `Getting Started` sample, for example, on Bolt 1.2.9 and send us the _complete_ logs of server and client?

Keep in mind that the NAT punch is not guaranteed to always work.

**Comment by dushukai** [comment]
[Server.log](https://github.com/BoltEngine/Bolt-Tracker/files/3458420/Server.log)
[Client.log](https://github.com/BoltEngine/Bolt-Tracker/files/3458421/Client.log)

**Comment by ramonmelo** [comment]
@dushukai 
Your logs are from different connection process. The server is creating the session `ae7090b2-b34c-49e3-827b-8326affab2cd`, but the client is connecting to session `3dbb217e-9209-4c80-9ce7-b1842629ba51`. 

In order to better understand the issue, we need the corresponding logs from the same connection attempt.

**Comment by dushukai** [comment]
[Server.log](https://github.com/BoltEngine/Bolt-Tracker/files/3474600/Server.log)

**Comment by dushukai** [comment]
[Client.log](https://github.com/BoltEngine/Bolt-Tracker/files/3474601/Client.log)

**Comment by ramonmelo** [comment]
Hello @dushukai,

Looking at the logs you sent, it seems you are indeed able to connect, not directly, but via the relayed connection. Also, one of your peers is able to receive and reply in the punch process, but the other doesn't. This is an expected behavior on some network configurations as some routers can block traffic between the peers. You can read more about the NAT punch process [here](https://bford.info/pub/net/p2pnat/) and [here](https://doc.photonengine.com/en-us/bolt/current/connection-and-authentication/bolt-connection-process).

Can you check again using our sample game linked [here](https://www.dropbox.com/s/bmgrutvwo17qrrk/BoltConnectionTest_apps.zip?dl=0)? And send the logs?

**Comment by ramonmelo** [comment]
Closing, as there is no response from the dev.
